<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="9.0.1.1" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Stabby.AudioCapture\x64\Release\*.dll" CopyToOutputDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
    <Content Include="LICENSE-ProcessAudioCapture.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
